### ISSUE TITLE
Import Error for module object_detection.proto

### ISSUE THREAD

**Issue by zakirhunter** [ShreyAmbesh/Traffic-Rule-Violation-Detection-System#5]
Where Can I GET The Module object_detection.protos
It gives me an error 

Traceback (most recent call last):
  File "VehicleMoniter.py", line 40, in <module>
    from utils import label_map_util
  File "/home/user/Desktop/IMP/Traffic-Rule-Violation-Detection-System-master/utils/label_map_util.py", line 22, in <module>
    from object_detection.protos import string_int_label_map_pb2
ModuleNotFoundError: No module named 'object_detection'

**Comment by ShreyAmbesh** [comment]
Follow the guidelines for installing object detection. [https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md](url)
