### ISSUE TITLE
ImportError: cannot import name 'string_int_label_map_pb2'

### ISSUE THREAD

**Issue by FerdinaKusumah** [ShreyAmbesh/Traffic-Rule-Violation-Detection-System#7]
`
Traceback (most recent call last):
  File "VehicleMoniter.py", line 40, in <module>
    from utils import label_map_util
  File "/Users/ferdinakusumah/Development/API/machine-kearning/license-plate-recognition/vehicle_detection/utils/label_map_util.py", line 22, in <module>
    from object_detection.protos import string_int_label_map_pb2
ImportError: cannot import name 'string_int_label_map_pb2'
`
Is any wrong in my configuration?
Im sorry my english not good enough

**Comment by ShreyAmbesh** [comment]
Did you install the object detection properly if not check it and try to reinstall it.

**Comment by hashneo77** [comment]
Hi, I'm also receiving the same error. Could you provide an info on how to install the object detection models
