### ISSUE TITLE
Exception?

### ISSUE THREAD

**Issue by Midnight1155** [ShreyAmbesh/Traffic-Rule-Violation-Detection-System#9]
Exception in thread Thread-11:
Traceback (most recent call last):
  File "C:\Users\Yongj\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Yongj\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "vehiclemoniter.py", line 72, in getLicensePlateNumber
    X1=js['results'][0]['coordinates'][0]['x']
IndexError: list index out of range
![issue1](https://user-images.githubusercontent.com/34037204/56151820-b7106d00-5fe4-11e9-8806-8e04b548deed.PNG)

**Comment by ShreyAmbesh** [comment]
It's happening because many subsequent requests are being sent to the openalpr api. You can put the requests in a queue and make the network api calls after a particular interval of time.

**Comment by NayanDoshi** [comment]
same problem happens with me also

please help
